name: deploy
on:
  push:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to develop
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ${{ secrets.PATH }}
          mkdir -p ../bak
          echo "backup"
          cp -r . ../bak/$(date +'%Y-%m-%d-%H-%M-%S')
          rm -rf ./*
          git clone https://github.com/mobeicanyue/www.ovvv.top.git
          mv www.ovvv.top/* .
          rm -rf www.ovvv.top
          echo "deploy success"
          exit
